services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.services.app.loadbalancer.server.port=8081"
    deploy:
      replicas: 3
    ports:
      - "8082:8081"

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8080"
    ports:
      - "8080:8080"
      - "8082:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
