## Masko ## 
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.services.app.loadbalancer.server.port=4000"
    deploy:
      replicas: 3
    expose:
      - "4000"  # musste den Port ändern
    networks:
      - web

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:4000"
    ports:
      - "4000:4000"  # App = http://localhost:4000
      - "4080:8080"  # Traefik-Dashboard = http://localhost:4080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web:
    driver: bridge
